### ISSUE TITLE
compile error when pip install submodules/raytracing

### ISSUE THREAD

**Issue by Hregl** [fudan-zvg/ref-gaussian#2]
error discribe:
     C:\Program Files (x86)\eigen3\Eigen\src/Core/arch/CUDA/Half.h(243): error: more than one operator "-" matches these operands:
                  built-in operator "arithmetic - arithmetic"
                  function "operator-(const __half &, const __half &)"
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include\cuda_fp16.hpp(254): here
                  operand types are: Eigen::half - const Eigen::half

      C:\Program Files (x86)\eigen3\Eigen\src/Core/arch/CUDA/Half.h(549): error: more than one operator "-" matches these operands:
                  built-in operator "arithmetic - arithmetic"
                  function "operator-(const __half &, const __half &)"
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include\cuda_fp16.hpp(254): here
                  operand types are: const Eigen::half - const Eigen::half
cuda:11.7
eigen:3.3.7

**Comment by z-x-j** [comment]
我使用cuda11.8  pytorch用作者提供的torch==2.0.0
torchvision==0.15.0可以正常编译，训练

**Comment by yyhosmium64** [comment]
This code works well on CUDA 11.7 & torch==2.0.0 & torchvision==0.15.0, Ubuntu docker environment. 

I am currently looking into this code, but I am not sure if it will work in a Windows environment.

**Comment by CodeJfeng** [comment]
my solution “Eigen Error" 
apt-get install libeigen3-dev

**Comment by XDzzzzzZyq** [comment]
For CUDA with a higher version, it is possible to use https://github.com/secantalpha/raytracing for alternation.
